version: '3'
services:
    cassandra:
        container_name: cassandra
        build: .
        restart: always
        ports:
            - "7000:7000"
        volumes:
            - ${PWD}/volumes/cassandra:/var/lib/cassandra
    debugger:
        image: panupongdeve/debugger:latest